config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  resources :projects do
    resources :rewards, only: [:new, :create, :destroy]
  end

  resources :rewards, only: [] do
    resources :pledges, only: [:new, :create]
  end 

  resources :users do
    resources :pledges, only: [:index, :destroy]
  end

  resources :user_sessions

  get 'forgot_password' => 'user_sessions#forgot_password'
  post 'submit_forgot_password' => 'user_sessions#submit_forgot_password'

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/claim.rb
class Claim < ActiveRecord::Base
	belongs_to :reward
	belongs_to :user #added by avi
end

app/models/pledge.rb
 class Pledge < ActiveRecord::Base
	belongs_to :reward
	belongs_to :user #added by avi
  	delegate :price, to: :rewards
end

app/models/pledges.rb
class Pledge < ActiveRecord::Base
	belongs_to :reward
	belongs_to :user #added by avi
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	has_many :rewards
  	has_many :pledges, through: :rewards
  	validates :name, :goal, :description, :start_date, :end_date, presence: true

	accepts_nested_attributes_for :rewards, reject_if: :all_blank, allow_destroy: true

	def completed
		if Datetime.now >= @project.end_date do |p|
			p.active = false
		end
	  end
	end

 	def amount_raised
  		self.rewards.sum(:price)
  	end

end

app/models/reward.rb
class Reward < ActiveRecord::Base
	belongs_to :project
	has_many :pledges
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :projects 
	#has_many :projects, through: :claims # commenting this allows user1.projects << proj1. Otherwise getting an error Active record through association
	has_many :rewards, through: :pledges # re-added
	has_many :pledges
	has_many :backed_projects, through: :rewards, source: :project, class_name: "Project"


	authenticates_with_sorcery!

	validates :password, length: { minimum: 3 }, if: -> { new_record? || changes["password"] }
	validates :password, confirmation: true, if: -> { new_record? || changes["password"] }
	validates :password_confirmation, presence: true, if: -> { new_record? || changes["password"] }

	validates :email, uniqueness: true

	accepts_nested_attributes_for :pledges, reject_if: :all_blank, allow_destroy: true

	def pledged_amount(project)
		amount = 0
		self.pledges.each do |pledge|
			amount += pledge.reward.price if pledge.reward.project == project  
		end
		return amount
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :require_login
  helper_method :current_user

  private
  def not_authenticated
  	redirect_to login_path, alert: "Please login first"
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      return nil
  end
end


  def authenticate_user
    unless current_user
      redirect_to '/login'
    end
  end

end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
before_action :require_login


def new
	@pledge = Pledge.new(reward_id: params[:reward_id])
    @current_user.pledges << @pledge

    if @pledge.save
		redirect_to user_path(current_user)    
	else
      	render 'project_path'	
    end
 
end

  def create


  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
before_action :require_login

	def new
		@project = Project.new
	end


	def create
		@project = Project.new(project_params)
		@project.user = current_user

		if @project.save
      		redirect_to project_path(@project), notice: "Successfully created the product."
    	else
      		render :new
    	end
	end

	def show
		 @project = Project.find(params[:id])
	end


  	def index
  		@projects = Project.all
  	end


	def edit
		@project = Project.find(params[:id])
	end


	def update
		@project = Project.find(params[:id])
		if @project.update_attributes(project_params)
			redirect_to project_path(@project)
		else 
			render :edit
		end 
	end


	def destroy
	end

private

  def project_params
    params.require(:project).permit(:name, :start_date, :end_date, :goal, :description, :active, rewards_attributes: [:id, :price, :title, :_destroy, :description])
  end

end


#@project = @temp_user.projects.build(project_params)
#@temp_user.projects <<  @project
#@project = @temp_user.build_project(project_params)

app/controllers/reward_controller.rb
class RewardController < ApplicationController
before_action :require_login

def show
  @reward = Reward.find(params[:id])

end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
	skip_before_action :require_login, except: [:destroy]

	def new
		@user = User.new
	end

	def create
		if @user = login(params[:email], params[:password])
			redirect_back_or_to(:users, notice: 'Login successful')
		else
			flash.now[:alert] = 'Login failed'
			render action: 'new'
		end
	end

	def forgot_password
	end


	def submit_forgot_password
		@user = User.where(email: params[:email]).first
		 if @user
		 	@user.deliver_reset_password_instructions!
		 else
		 	flash.now[:alert] = 'Email not founded'
		 end
		 redirect_to(root_path, :notice => 'Instructions have been sent to your email.')
	end

	def destroy
		logout
		redirect_to(:users, notice: 'Logged out!')
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_action :require_login, only: [:index, :new, :create]

	def show
  		@projects_owned = current_user.projects.all
  		# @projects_backed = current_user.projects.
	end


	def new
		@user= User.new
	end

	def index
		@users = User.all
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to(:users, notice: 'User was successfully created')
		else
 			render 'new'
		end
	end

	def update
    @user = User.find(params[:id])
	    if @user.update_attributes(user_params)
	     	redirect_to root_path
	    else
	      render 'edit'
	    end
    end

	def edit
		@user = User.find(params[:id])
	end

	private

	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/claim_helper.rb
module ClaimHelper
end

app/helpers/pledge_helper.rb
module PledgeHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/reward_helper.rb
module RewardHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jumpstarter</title>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <link href='https://fonts.googleapis.com/css?family=Lato:400,300,700' rel='stylesheet' type='text/css'>

  <!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

	  <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>



  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">jumpStarter</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/"><span class="glyphicon glyphicon-cloud"></span> Home</a></li>
        <li><a href="/#projects_display"><span class="glyphicon glyphicon-file">Projects</a></li>


		<% if current_user %>
        <li><%= link_to '<span class="glyphicon glyphicon-user"></span> My Profile'.html_safe , user_path(current_user.id)%>
        </li>
        <% else %>
        <li><a href="sessions/new">Sign In</a></li>
        <li><a href="users/new">Sign Up</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
	<div>
		<p id="notice"><%= flash[:notice] %></p>
		<p id="alert"><%= flash[:alert] %></p>
	</div>

<div id="spacer">
</div>

	<%= yield %>

</body>
</html>

app/views/pledges/new.html.erb
<h1> Create a new pledge </h1>


<%= form_for @pledge do |p| %>
	<%= f.label :submit %>
	<%= f.submit "Create Pledge" %>
<% end %>

app/views/projects/_form.html.erb
<div class="form">
  <%= form_for(@project) do |f| %>

  <% if @project.errors.any? %>
      <div id="error">
        <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
        
        <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>

      </div>
    <% end %>

    <div class="labels-and-inputs">
      <p class="label"><%= f.label :name %></p>
      <p class="input" id="name"> Name: <%= f.text_field :name %></p>

      <p class="label"><%= f.label :start_date %></p>
      <p class="input" id="start_date"> Start Date: <%= f.date_select :start_date %></p>
      
      <p class="label"><%= f.label :end_date %></p>
      <p class="input" id="end_date"> End Date: <%= f.date_select :end_date %></p>

      <p class="label"><%= f.label :goal %></p>
      <p class="input" id="goal"> Goal: <%= f.number_field :goal %></p>

      <p class="label"><%= f.label :description%></p>
      <p class="input" id="description"> Description: <%= f.text_area :description %></p>

      <p class="label"><%= f.label :active %></p>
      <p class="input" id="active"><%= f.select :active, [['Active',true],['Inactive',false]] %></p>
    </div>

    REWARDS:
      <ul>
        <%= f.fields_for :rewards do |reward| %>
          <%= render 'reward_fields', :f => reward %>
        <% end %>
      </ul>
    <%= link_to_add_association 'Add Reward', f, :rewards, 'data-association-insertion-method' => 'append' %>

    <div id="rewards">

      List of Rewards:
        <ul>
          <%= f.fields_for :rewards do |ff| %>
            <%= render partial: 'reward_fields', locals: {:f => ff} %>
          <% end %>
        </ul>

       <div class="links">
         <%= link_to_add_association 'Add Reward', f, :rewards %>
       </div>
    </div>

    

	  <div class="submit">
      <%= f.submit %>
  	</div>
  <% end %>
</div>

app/views/projects/_project.html.erb
<ul>
	<li>
	<h1>
  <%= "#{project.name}" %> </h1> </br>

  <%= "#{project.description}" %> </br>
  <%= "#{project.start_date}" %> </br>
  <%= "#{project.end_date}" %> </br>

	</li>
</ul>

app/views/projects/_reward_fields.html.erb
<li>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :price %>
    <%= f.number_field :price %>

    <%= f.label :description %>
    <%= f.text_field :description %>
</li>

app/views/projects/edit.html.erb
<h1> Edit Project </h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active pic_holder">
      <img src="http://www.tumotech.com/wp-content/uploads/2014/05/fire-hands-super-hq-302329edited.jpg" alt="...">
      <div class="carousel-caption">
          <h3 class="quotation">Inspire Change</h3>
      </div>
    </div>
    <div class="item pic_holder">
      <img src="http://viavox.pl/wp-content/uploads/2015/06/HR-Technology-Trends.jpg" alt="...">
      <div class="carousel-caption">
          <h3 class="quotation">Build a Better Future</h3>
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div> <!-- Carousel -->

<a name="projects_display">
<div class="row" id="projects_title">
</a>
	<div id="jumpstarter_title">
		<h1 id="jumpstarter_text"> Current Projects </h1>
	</div>
</div>

<div id="projects_body">
	<div id="project_container">
		<% @projects.each do |p| %>
		<div class="project_box">
			<img class="placeholder_img" src="https://placehold.it/2400x1600">
			<div class="text_holder">
				<p class="project_name"><%= link_to p.name, project_path(p) %> </p></p>
				<p class="description"> <%= p.description %></p>
				<p class="end_date">End Date: <%= p.end_date.to_s.to_date %></p>
				<p class="goal">Fundraising Goal: <%= p.goal %></p>
			</div>
		</div>
		<% end %>
	</div>
</div>


<script>
    $('.carousel').carousel({
        interval: 6000
    })
</script>

app/views/projects/new.html.erb
<div id="backg">


<h1 id="newp">Create a new project</h1>



	<h5 id="newform">
	  <%= render 'form' %>
	  <%= link_to 'Back', projects_path %>
	</h5>

</div>

app/views/projects/show.html.erb
<div class="row project_page_body">

<div class="col-md-9 project_page_container">
	<img class="project_page_image" src="http://www.placehold.it/400x400">
	<p class="project_page_name margin"><%= link_to @project.name, project_path(@project) %> </p> </p>
	<p class="project_page_summary margin"><%= @project.description %></p>
	<p class="project_page_start margin">Start Date: <%= @project.start_date.to_date %></p>
	<p class="project_page_end margin">End Date: <%= @project.end_date.to_date %></p>
	<p class="project_page_goal margin">Goal: <%= @project.goal %></p>
	<p class="project_page_owner margin">Owner: <%= @project.user.email %></p>
	<p id="amount-raised"> Total Raised: $<%= @project.amount_raised %> </p>
</div>


<div class="col-md-3 reward_container"> 
	<h2 id="rewards_title"> Back Us! </h2>
	<% if @project.rewards.any? %>

		<% @project.rewards.each do |reward| %>

		<div class="reward_child">
			<p class="reward_title"><%= reward.title %></p>
			<p class="reward_price">$<%= reward.price %></p>
			<p class="reward_desc"><%= reward.description %></p>
			<p class="purchase"><%= link_to "Purchase this reward", new_reward_pledge_path(reward) %></p>
		</div>
		<% end %>

	<% else %>

	<p> No rewards have been setup for this project! </p>

	<% end %>

<p id="pledged">Pledged Amount: </p>
<p id="amount_pledged"> $<%= @current_user.pledged_amount(@project) %> </p>
</div>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/forgot_password.html.erb
<h1>Find your account</h1>

<h5>Enter your email</h5>

<%= form_tag ('submit_forgot_password') do %>
   <div>
        <label for="mail">E-mail:</label>
        <input name="email" type="email" id="mail" />
    </div>

  <div class="button">
        <button type="submit">Search</button>
    </div>


<% end %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

<%= link_to 'Forgot Password', forgot_password_path %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

<div class="field">
	<%= f.label :name %><br />
	<%= f.text_field :name %>
</div>
<div class="field">
	<%= f.label :email %><br />
	<%= f.text_field :email %>
</div>
<div class="field">
	<%= f.label :password %><br />
	<%= f.password_field :password %>
</div>
<div class="field">
	<%= f.label :password_confirmation %><br />
	<%= f.password_field :password_confirmation %>
</div>
<div class="actions">
	<%= f.submit "Register" %>
</div>

<% end %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>
<%= render 'form' %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/users/show.html.erb
<div class="spacer">
</div>

<div class="row">
	<div class="col-md-2"></div>
		<div class="col-md-8">
			<p id="my_profile"> My Profile </p>
			<p id="my_name"> Name: <%= current_user.name %></p>
			<p id="my_name"> Email: <%= current_user.email %></p>
			
		</div>
	<div class="col-md-2"></div>
</div>

<hr>


<div class="row">
<div class="col-md-2"></div>

	<div class="col-md-8">
	<h2 id="owner_of">My Projects</h2>
			<% if @projects_owned.any? %>
				<div id="owner_projects_container">
					<% @projects_owned.each do |project| %>
						<div class="a_project">
							<img class="proj_placeholder_img" src="http://www.placehold.it/800x800">
							<p class="proj_name"><%= link_to project.name, project_path(project) %> </p>
							<p class="proj_descrip"><%= project.description %> </p>
							<p class="proj_start">Start Date: <%=project.start_date.strftime("%b %d, %Y")  %></p>
							<p class="proj_end">End Date: <%=project.end_date.strftime("%b / %d / %Y")  %></p>
							<p class="proj_active">Active: <%=project.active.to_s.capitalize! %></p>
							<p class="proj_goal">Goal: $<%=project.goal %></p>
							
						</div>
					<% end %>
				</div>
			<% else %>
				<p>No Projects for <%= @current_user.email%></p>
			<% end %>
	</div>
	<div class="col-md-2">
	</div>
</div>
<hr>

<div class="row" id="my_projects">
	<div class="col-md-2">
	</div>
	<div class="col-md-8">
		<h2 id="project_backed">Projects Backed: </h2>

		<% if @current_user.backed_projects.any? %>
			<% @current_user.backed_projects.uniq.each do |proj| %>

				<div class="a_project">
					<img class="proj_placeholder_img" src="http://www.placehold.it/800x800">
					<p class="proj_name"><%= link_to proj.name, project_path(proj) %> </p>
					<p class="proj_descrip"><%= proj.description %> </p>
					<p class="proj_start">Start: <%=proj.start_date.strftime("%b / %d / %Y")  %></p>
					<p class="proj_end">End: <%=proj.end_date.strftime("%b %d, %Y")  %></p>
					<p class="proj_active">Active : <%=proj.active.to_s.capitalize! %></p>
					<p class="proj_goal">Goal: $<%=proj.goal %></p>

				</div>	
			<% end %>
		<% else %>
			<p>No Backed Projects for <%= @current_user.email%></p>
		<% end %>
	</div>
	</div>